### ISSUE TITLE
ical4j dependency

### ISSUE THREAD

**Issue by JavierMartinezRojo** [jpotts/share-inbound-invites#4]
Hi Jeff, 
There is an error related with ical4j dependency I fixed using <groupId>org.mnode.ical4j</groupId> (replacing <groupId>ical4j</groupId> existing one in pom.xml)
I hope it helps!

**Comment by jpotts** [comment]
What was the error you were seeing?

**Comment by JavierMartinezRojo** [comment]
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/ical4j/ical4j/1.0.6/ical4j-1.0.6.pom
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/ical4j/ical4j/1.0.6/ical4j-1.0.6.pom
Downloading: https://repo.maven.apache.org/maven2/ical4j/ical4j/1.0.6/ical4j-1.0.6.pom
[WARNING] The POM for ical4j:ical4j:jar:1.0.6 is missing, no dependency information available
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public/ical4j/ical4j/1.0.6/ical4j-1.0.6.jar
Downloading: https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/ical4j/ical4j/1.0.6/ical4j-1.0.6.jar
Downloading: https://repo.maven.apache.org/maven2/ical4j/ical4j/1.0.6/ical4j-1.0.6.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.340 s
[INFO] Finished at: 2016-08-24T18:31:18+02:00
[INFO] Final Memory: 22M/1027M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project inbound-invites-repo: Could not resolve dependencies for project com.metaversant:inbound-invites-repo:amp:1.0-SNAPSHOT: Could not find artifact ical4j:ical4j:jar:1.0.6 in alfresco-public (https://artifacts.alfresco.com/nexus/content/groups/public) -> [Help 1]

**Comment by jpotts** [comment]
Thanks for submitting this, Javier. It's committed on the 5.1.e branch.

**Comment by JavierMartinezRojo** [comment]
Thanks to you for share it!
