### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by akashdubey251996** [jpotts/share-inbound-invites#7]
While runnig the command mvn install i am getting the error:

gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Share Inbound Calendar Invites 1.2.1-SNAPSHOT:
[INFO] 
[INFO] Share Inbound Calendar Invites ..................... FAILURE [  6.995 s]
[INFO] inbound-invites-repo Repository AMP project ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.770 s
[INFO] Finished at: 2020-08-20T17:18:58+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (sign-artifacts) on project inbound-invites: Exit code: 2 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jpotts** [comment]
Thanks, I had added some items to the build so that the artifacts can be signed and pushed to Maven Central. These are obviously not applicable to those without the code signing key. As of commit 9b77018 I've moved those to a profile to get them out of the way.

Thanks for reporting the issue @akashdubey251996
